on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Azure Pages
    steps:
    - uses: actions/checkout@v1
    - name: Build And Deploy
      id: hello
      uses: miwebst/basic-deploy-task@master
      with:
        app-location: 'app'
